io:
  dataset_type: science
  output_dir: snapshots
  run_tag: yuanbiao-colab-test
training:
  num_train_epochs: 3
  gradient_accumulation_steps: 2
  learning_rate: 0.0002
  batch_size: 4
  optimizer: "paged_adamw_32bit"
model:
  use_bf16: false
  use_flash_attention2: false
  model_name: NousResearch/Llama-2-7b-hf
  adapter: lora
misc:
  seed: 42
  token: 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
